server:
  application:
    name: "eglobal"
  port: 8090

spring:
  application:
    name: "eglobal"

  datasource:
    url: jdbc:mysql://eglobal.c7kaekmmqyel.us-east-2.rds.amazonaws.com/users
    username: admin
    password: adminadmin
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
